spring:
  #redis连接设置
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      max-active: 30
      max-idle: 10
      min-idle: 3
      max-wait: 3000
  #数据库连接池连接设置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 950404
    url: jdbc:mysql://localhost:3306/hospital?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    ##初始连接数，默认0
    initialSize: 10
    #最大连接数，默认8
    maxActive: 30
    #最小闲置数
    minIdle: 10
    #获取连接的最大等待时间，单位毫秒
    maxWait: 2000
    #缓存PreparedStatement，默认false
    poolPreparedStatements: true
    #缓存PreparedStatement的最大数量，默认-1（不缓存）。大于0时会自动开启缓存PreparedStatement，所以可以省略上一句设置
    maxOpenPreparedStatements: 20
  #日期格式化设置
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd

#mybatis映射文件设置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

#设置虚拟路径和端口
server:
  port: 8088
  servlet:
    context-path: /hospital